### ISSUE TITLE
Overflowing Grid di bagian 'Produk Paling Laris'

### ISSUE THREAD

**Issue by bramadityaw** [WayuAji30/Butchery#3]
Bisa diliat di gambar:
![image](https://github.com/WayuAji30/Butchery/assets/138552402/fd99f132-c1e3-4464-8501-ad5832df04e5)

Sebenarnya, tinggal dikasih breakpoint supaya item terakhir disembunyikan. Tailwind gak support breakpoint pake max-width masalahnya

**Comment by wahyumustikaaji** [comment]
Udah bisa blm?

**Comment by bramadityaw** [comment]
masalah sebenarnya adalah width dari viewport device gue. gue cek pake javascript:
>> const width = window.innerWidth; 
>> console.log(width)
1366

mau pake media query segede apapun, tetep aja bakal overflow.

untuk sementara, gue bikin grid gap-nya 130px hanya jika viewport width di viewport lg
